### ISSUE TITLE
Services variable not working with hiera hash. Expects an array of hashes it seems.

### ISSUE THREAD

**Issue by brahama** [solarkennedy/puppet-consul#230]
Hi guys,

I am trying to make the hash for services work but i see in the conf json, that the result config is like this:
```
"services":{"http-pub":{"id":"vhost80","name":"http-pub","port":80},"http-pub443":{"id":"vhost443","name":"http-pub","port":443}}"services":{"http-pub":{"id":"vhost80","name":"http-pub","port":80},"http-pub443":{"id":"vhost443","name":"http-pub","port":443}}
```

when it shouhld be like this:

```
"services": [
        {"id":"vhost80","port":80, "name": "http-pub"},{"name":"http-pub","id":"vhost443","port":443}],
```

Or am i doing somethign wrong?

My hiera conf is like this:

```
my_profile::services" : { "http-pub":{ "name":"http-pub", "port":80, "id": "vhost80"},"http-pub443":{ "name": "http-pub", "port":443, "id":"vhost443"}},
```

Cheers!

**Comment by solarkennedy** [comment]
The `services` entrypoint in puppet-consul just uses `create_resources`. It is not intended to map directly into consul json.

On the config on disk, I would expect to manifest as different files per service.

Your input to puppet consul is a *hash*, there the keys are the service names and the values are the inputs to `consul::service`.

```
consul::services: 
 "http-pub":    {"port":80, "id":"vhost80"}
 "http-pub443": {"port":443,"id":"vhost443"}
```

**Comment by brahama** [comment]
Hey! thanks for the response... right now i hve it like you mention. But that involves calling specifically the entrypoint for that services... I want to use hiera so i dont need to call that specifically in the module. I am trying to use the services variable that says it needs a hash. Sorry, im kinda new so maybe i didnt explained correctly... 

validate_hash($services)

So in hiera i have to fill the variable like its a list then?

Cheers!

**Comment by bflad** [comment]
Hi! As Kyle mentioned, and gave an example. The way the hiera is setup requires a pattern that translates into:
```
resource-title:
  resource-attribute1: value1
  resource-attribute2: value2
```

So for example in our production hiera, we have a setup like:
```
consul::services:
  service1:
    address: "%{::ipaddress}"
    checks:
      - http: http://localhost:29536/status
        interval: 5s
    port: 29536
    tags:
      - "asg:%{::asg}"
      - "datacenter:%{::datacenter}"
      - "ec2_placement_availability_zone:%{::ec2_placement_availability_zone}"
      - "server_role:%{::server_role}"
  service2:
    address: "%{::ipaddress}"
    checks:
      - http: http://localhost:8857/status
        interval: 5s
    port: 8857
    tags:
      - "asg:%{::asg}"
      - "datacenter:%{::datacenter}"
      - "ec2_placement_availability_zone:%{::ec2_placement_availability_zone}"
      - "server_role:%{::server_role}"
```

Of course your services and checks will be unique compared to my example, but generally this is how hiera works with `create_resources()` calls under the hood, like how its used in this module. Hope this helps!
