### ISSUE TITLE
systemd Client Nodes Not Properly Leaving Cluster on Shutdown

### ISSUE THREAD

**Issue by bflad** [solarkennedy/puppet-consul#282]
## Details

OS: Ubuntu 16.04
Consul: 0.6.4 and 0.7.0
Puppet: 4.6.1
Puppet Module: 1.1.0
Puppet Config:

```
consul::config_hash:
  client_addr: 0.0.0.0
  data_dir: /opt/consul
  datacenter: "datacenter"
  dogstatsd_addr: "localhost:8125"
  encrypt: --OMITTED--
  enable_syslog: true
  log_level: INFO
  retry_join:
    - "consul.example.com"
consul::pretty_config: !!bool true
consul::version: 0.7.0
```
## Behavior

On shutting down servers running the Consul client on Ubuntu 16.04, they show up as `failed` in `consul members` and the web UI afterwards. This was not an issue in 14.04 using Upstart where they'd be gracefully shutdown, e.g. `left`. Tried both Consul 0.6.4 and Consul 0.7.0 (with its new leave defaults for clients), to no avail. Seems like maybe the systemd service configuration might not be properly ordered.
