### ISSUE TITLE
Issues with default data-dir post-#292

### ISSUE THREAD

**Issue by jamtur01** [solarkennedy/puppet-consul#307]
The #292 merge breaks the module if you don't use `/opt/consul` as the data directory.

```puppet
   amazon-ebs: Notice: /Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.2]: Dependency File[/opt/consul/archives] has failures: true
    amazon-ebs: Error: Cannot create /opt/consul/archives; parent directory /opt/consul does not exist
    amazon-ebs: Error: /Stage[main]/Consul::Install/File[/opt/consul/archives]/ensure: change from absent to directory failed: Cannot create /opt/consul/archives; parent directory /opt/consul does not exist
    amazon-ebs: Notice: /Stage[main]/Consul::Install/Archive[/opt/consul/archives/consul-0.7.2.zip]: Dependency File[/opt/consul/archives] has failures: true
    amazon-ebs: Notice: /Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.2/consul]: Dependency File[/opt/consul/archives] has failures: true
    amazon-ebs: Notice: /Stage[main]/Consul::Install/File[/usr/local/bin/consul]: Dependency File[/opt/consul/archives] has failures: true
    amazon-ebs: Warning: /Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.2]: Skipping because of failed dependencies
    amazon-ebs: Warning: /Stage[main]/Consul::Install/Archive[/opt/consul/archives/consul-0.7.2.zip]: Skipping because of failed dependencies
    amazon-ebs: Warning: /Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.2/consul]: Skipping because of failed dependencies
    amazon-ebs: Warning: /Stage[main]/Consul::Install/File[/usr/local/bin/consul]: Skipping because of failed dependencies
```

My config hash:

```yaml
consul::config_hash:
  data_dir: '/var/consul'
  datacenter: 'redacted'
  encrypt: 'redacted'
  enable_syslog: true
  rejoin_after_leave: true
  log_level: INFO
  retry_join_ec2:
    tag_key: Flag
    tag_value: consul
```
