### ISSUE TITLE
Add support for gRPC

### ISSUE THREAD

**Issue by spuder** [solarkennedy/puppet-consul#498]
I'm trying to setup a consul health check for grpc services as shown here:

https://www.consul.io/docs/agent/checks.html
```
{
  "check": {
    "id": "mem-util",
    "name": "Service health status",
    "grpc": "127.0.0.1:12345",
    "grpc_use_tls": true,
    "interval": "10s"
  }
}
```

However, when I try the following hiera data: 

```
consul::services:
  natsd:
    id: natsd
    name: natsd
    checks:
    - id: port
      name: natsd running
      grpc: ":::4244"
      grpc_use_tls: false
      interval: 10s

```

I get error:

```
Error while evaluating a Resource Statement, Evaluation Error:   
Error while evaluating a Function Call, One of ttl, script, tcp, or http must be defined.
```
