### ISSUE TITLE
Is there a way to encrypt or hide the acl_api_token value?

### ISSUE THREAD

**Issue by jhur7** [solarkennedy/puppet-consul#544]
I have checked in my acl_api_token into various places in my Hiera yaml files.  I'd like to be able to either look up my token or obfuscate/ecnrypt the acl_api_token.  Is there a way to do this or am I missing something obvious in the module?  Here's a snippet of one of my Hiera files with the acl_api_token redacted.  

Thank You.

```
consul::policies:
  'Consul_Node_Policy':
    description: "Consul Node policy, generated by puppet"
    rules:
      - resource: agent_prefix
        segment: ""
        disposition: "write"
      - resource: node_prefix
        segment: ""
        disposition: "write"
      - resource: service_prefix
        segment: ""
        disposition: "read"
      - resource: session_prefix
        segment: ""
        disposition: "read"
    acl_api_token: “REDACTED”
```
